### ISSUE TITLE
Add my own shortcut key

### ISSUE THREAD

**Issue by bobrocke** [lkcampbell/brackets-indent-guides#20]
If I want to add my own shortcut to toggle the display of indent guides, is there a command I can target? Something like `view.toggleIndentGuide`?

**Comment by lkcampbell** [comment]
The command id is `lkcampbell.toggleIndentGuides`. But, really, what I need to do is add the shortcut key back in again now that customized key mapping is available again. Long, long ago, when this extension was first created, we didn't have customized key mapping and I removed the shortcut key because it kept conflicting with other shortcuts. I guess I can put it back in now.

**Comment by lkcampbell** [comment]
Oh...actually, now that I took the took to review key mapping...yeah, all you have to do is add the keymap override and connect it to command `lkcampbell.toggleIndentGuides`. I will update the documentation in this extension with the id of the command an example of how to create the key map, thanks. Leaving this issue open as a reminder until I finish it.

**Comment by bobrocke** [comment]
Works like a charm. Thanks!

**Comment by lkcampbell** [comment]
Updated custom key binding documentation.
