### ISSUE TITLE
Bracket indent guide is not showing

### ISSUE THREAD

**Issue by AtlantaKid** [lkcampbell/brackets-indent-guides#42]
I just installed Bracket " Release 1.14 build 1.14.0-17740 (release 329d08ffc) 
build timestamp: Fri Apr 26 2019 18:14:42 GMT+0100 " and installed indent guide and no guide is showing up, I am using the default dark theme. 

![2019-05-09](https://user-images.githubusercontent.com/43429127/57491594-804c1080-728b-11e9-926f-d8d08592a894.png)

**Comment by lkcampbell** [comment]
@AtlantaKid need more info as I am not seeing an issue in Brackets 1.14.

What OS are you using?

If you disable all of your other extensions and just use indents guides, does it work?

**Comment by JulianSteinmann** [comment]
I had this too, it is likely that there's a plugin conflict between the two plugins Emmet + Intend Guides.

**Comment by JulianSteinmann** [comment]
Or in case you have not got Emmet installed I would deactivate all other plugins and see if it works then.

**Comment by nufrankz** [comment]
> @AtlantaKid need more info as I am not seeing an issue in Brackets 1.14.
> 
> What OS are you using?
> 
> If you disable all of your other extensions and just use indents guides, does it work?

There is a problem also with `BracketsToIX` [https://github.com/a-bentofreire/bracketstoix](url).
Tested with Brackets Release 1.14 v1.14.0-17740 (release 329d08ffc), Mojave.
Installing first `Brackets Indent Guides`, then `BracketsToIX` seems to work.
But I wasn't able to install `Emmet` after `Brackets Indent Guides` (error).
Interesting and thank you for developing this extension!

**Comment by lkcampbell** [comment]
@nufrankz, in regards to the Emmet problem, can you take a look at issue https://github.com/lkcampbell/brackets-indent-guides/issues/41 and see if it describes what you are seeing? I have not been able to repro the problem. Can you add to the discussion so i can track down the issue and fix it? I might need specific steps from you. I will reopen the bug.

**Comment by lkcampbell** [comment]
@AtlantaKid, I'm closing this bug as no repro. If you can provide me further information regarding your extensions, I will take a look at again. Thanks.

**Comment by lkcampbell** [comment]
I'm seeing the problem with the `BracketsToIX` extension, so I will look into fixing that separate from this issue.

**Comment by lkcampbell** [comment]
Okay, the conflict with the `BracketsToIX` extension isn't just with Indents Guides. I'm getting the same problem trying to install Beautify as well. Appears to be a localization problem, so I imagine any extension with multiple translated languages that is installed after the `BracketsToIX` extension is going to fail. I am following up with the extension owner at https://github.com/a-bentofreire/bracketstoix/issues/29.

**Comment by lkcampbell** [comment]
I did a few more tests and I get the same problem any time I try to install extensions that have translations after installing the `BracketsToIX` extension. The problem goes away after I uninstall the `BracketsToIX` extension.

There is a work around. If you disregard the error messages and restart Brackets, all of the extensions that errored out should still be there and should work correctly about the restart.

Update: I can't install the Emmet extension right after installing the `BracketsToIX` extension either, so that might be what is causing the Emmet problem as well.

**Comment by a-bentofreire** [comment]
I was able to trace the problem and fixed on `BracketstoIX` that caused conflit with other extensions.  
The offending code was `require.config` which was part, from what I remember, from the documented way to supporting i18n but either Brackets remove this requirement or it always caused conflict but it was never reported.   
The new version 3.7.1 of `BrackettoIX` is now available and it no longer causes this conflict.

**Comment by lkcampbell** [comment]
@a-bentofreire your fix works, thanks for responding so quickly. I understand, I have had changes to the core code of Brackets break extensions on more than one occasion myself.

@AtlantaKid, since this thread got derailed a bit from your original problem, we can reopen it or start a new thread if you are still having problems. I still need to know if you are using other extensions, though, so please try disabling your other extensions and see if this is still a problem, thanks.

For everyone else, install the new version of `BracketstoIX` and the installation problem with all of the above mentioned extensions will go away. Closing the issue.
